### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [the-nikidemus/grisha#1]
How did you get past [this issue](https://github.com/gradle/gradle/issues/18096)?

Thanks!

**Comment by judos** [comment]
Got the same error:

```
Failed to parse template script (your template may contain an error or be trying to use expressions not currently supported): startup failed:
     SimpleTemplateScript34.groovy: 1: Unexpected character: '"' @ line 1, column 13.
        out.print("""
```

I created a minimal example to reproduce the issue.
In my case it seems gradle kotlin dsl doesn't handle comments inside property files.

Either commenting out this in build.gradle.kts:
```
tasks.withType<ProcessResources> {
	filesMatching("*.properties") {
		expand("version" to version, "buildTimestamp" to LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")))
	}
}
```

Or removing this in application.properties:
```
#  \ \\\\\\\\n \\\\) test %m%n
```

Fixes the build.

See minimal reproducable example added:
Minimal Spring project: [demo.zip](https://github.com/the-nikidemus/grisha/files/9591875/demo.zip)
Full error running gradle: [logs.txt](https://github.com/the-nikidemus/grisha/files/9591876/logs.txt)
